const {
  ROPSTEN,
  RINKEBY,
  KOVAN,
  MAINNET,
  GOERLI,
  ROPSTEN_CODE,
  RINKEYBY_CODE,
  KOVAN_CODE,
  GOERLI_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  GOERLI_DISPLAY_NAME,
  CPX_MAINNET,
  CPX_TESTNET,
  CPX_MAINNET_CODE,
  CPX_TESTNET_CODE,
  CPX_MAINNET_DISPLAY_NAME,
  CPX_TESTNET_DISPLAY_NAME,
} = require('./enums')

// add cpx main,testnet 20190717 dadfkim@hanmail.net
const networkToNameMap = {
  [CPX_MAINNET]: CPX_MAINNET_DISPLAY_NAME,
  [CPX_TESTNET]: CPX_TESTNET_DISPLAY_NAME,
  [CPX_MAINNET_CODE]: CPX_MAINNET_DISPLAY_NAME,
  [CPX_TESTNET_CODE]: CPX_TESTNET_DISPLAY_NAME,
  [ROPSTEN]: ROPSTEN_DISPLAY_NAME,
  [RINKEBY]: RINKEBY_DISPLAY_NAME,
  [KOVAN]: KOVAN_DISPLAY_NAME,
  [MAINNET]: MAINNET_DISPLAY_NAME,
  [GOERLI]: GOERLI_DISPLAY_NAME,
  [ROPSTEN_CODE]: ROPSTEN_DISPLAY_NAME,
  [RINKEYBY_CODE]: RINKEBY_DISPLAY_NAME,
  [KOVAN_CODE]: KOVAN_DISPLAY_NAME,
  [GOERLI_CODE]: GOERLI_DISPLAY_NAME,
}

const getNetworkDisplayName = key => networkToNameMap[key]

// add checked network function 20190724 dadfkim@hanmail.net


module.exports = {
  getNetworkDisplayName,
}
